### ISSUE TITLE
Website is down :(

### ISSUE THREAD

**Issue by kmcquade** [glassechidna/trackiam#32]
It redirects to https://aktion.io/. I'm getting this error:

![image](https://user-images.githubusercontent.com/3422255/71485372-b7e9d780-27de-11ea-855f-691deb7eca27.png)

@aidansteele FYI

**Comment by ollytheninja** [comment]
Fixed :)

**Comment by kmcquade** [comment]
It's down again :/

**Comment by ollytheninja** [comment]
Noticed that yesterday, I'll have a look in a bit ;)

**Comment by kmcquade** [comment]
Cool, thanks @ollytheninja. Hope y'all are staying safe out there.

**Comment by ollytheninja** [comment]
I think someone deleted the AWS account we were using for DNS (@aidansteele ?)
Have reset it so should be back up in ~30minutes

**Comment by kmcquade** [comment]
😂

**Comment by ollytheninja** [comment]
Should be up for good now 😉 added to my monitoring as well
